version: "2"
#exclude_patterns:
#    - "coverage/" # only relevant on dev
#    - "**/node_modules/"
#    - "**/tests/"
checks:
    argument-count:
        config:
            threshold: 4
    complex-logic:
        config:
            threshold: 4
    file-lines:
        config:
            threshold: 250
    method-complexity:
        config:
            threshold: 5
    method-count:
        config:
            threshold: 20
    method-lines:
        config:
            threshold: 25
    nested-control-flow:
        config:
            threshold: 4
    return-statements:
        config:
            threshold: 4
    similar-code:
        config:
            threshold: # language-specific defaults. an override will affect all languages.
    identical-code:
        config:
            threshold: # language-specific defaults. an override will affect all languages.
plugins:
    eslint:
        enabled: true
        channel: "eslint-5"
        exclude_patterns:
            - "coverage/" # only relevant on dev
            - "**/node_modules/"
            - "**/tests/"
        config:
            extensions:
                - .js
                - .vue
    phpcodesniffer:
        enabled: true
    phpmd:
        enabled: true
        config:
            rulesets: "cleancode,codesize,controversial,design,unusedcode,phpmd.xml"
    sonar-php:
        enabled: true