version: '2.4'
services:
    nginx:
        build: ./docker/nginx
        volumes_from:
            - php:ro
        volumes:
            - ./docker/nginx/conf.d/dev.conf:/etc/nginx/conf.d/dev.conf
        expose:
            - 3000
            - 8080
        links:
            - node
        networks:
            default:
            static-network:
                ipv4_address: '172.50.0.4'
    php:
        build: ./docker/php
        working_dir: /app
        command: php-fpm -R
        user: ${UID}
        links:
            - mysql
        volumes:
            - .:/app
    mysql:
        image: mysql:5.7
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "123"
    node:
        image: node:12.10.0-alpine
        command: sh -c 'yarn install && yarn run dev && yarn run watch'
        working_dir: /app
        expose:
            - 3000
        volumes_from:
            - php

networks:
    static-network:
        driver: bridge
        ipam:
            config:
                - subnet: '172.50.0.0/24'
